export const campusData = [
  { "label": "Campus Apodi", "value": "AP" },
  { "label": "Campus Caicó", "value": "CA" },
  { "label": "Campus Natal - Cidade Alta", "value": "CAL" },
  { "label": "Campus Canguaretama", "value": "CANG" },
  { "label": "Campus Ceará-Mirim", "value": "CM" },
  { "label": "Campus Currais Novos", "value": "CN" },
  { "label": "Campus Natal - Central", "value": "CNAT" },
  { "label": "Campus Ipanguaçu", "value": "IP" },
  { "label": "Campus João Câmara", "value": "JC" },
  { "label": "Campus Avançado Jucurutu", "value": "JUC" },
  { "label": "Campus Lajes", "value": "LAJ" },
  { "label": "Campus Macau", "value": "MC" },
  { "label": "Campus Mossoró", "value": "MO" },
  { "label": "Campus Nova Cruz", "value": "NC" },
  { "label": "Campus Avançado Parelhas", "value": "PAAS" },
  { "label": "Campus Parnamirim", "value": "PAR" },
  { "label": "Campus Pau Dos Ferros", "value": "PF" },
  { "label": "Campus Santa Cruz", "value": "SC" },
  { "label": "Campus São Gonçalo Do Amarante", "value": "SGA" },
  { "label": "Campus São Paulo Do Potengi", "value": "SPP" },
  { "label": "Campus Avançado Natal-Zona Leste", "value": "ZL" },
  { "label": "Campus Natal - Zona Norte", "value": "ZN" }
]
