import type { Metadata } from "next";
import { Baloo_2, Inter } from "next/font/google";
import "@/styles/globals.css";

import NextAuthProvider from "@/components/providers/session-provider";
import {Toaster} from "@/components/ui/sonner";

const baloo2 = Baloo_2({
  variable: "--font-title",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-text",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="pt-BR">
       <body className={`${baloo2.variable} ${inter.variable} antialiased`}>
              <NextAuthProvider>
                  {children}
                  <Toaster />
              </NextAuthProvider>
          </body>
      </html>
  );
}
